In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('datasets/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le=LabelEncoder()

In [5]:
df['Species']=le.fit_transform(df['Species'])

In [6]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

#Create linear regression model

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
model=LinearRegression()

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x=df.drop(['Id','Species'],axis='columns')
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [11]:
y=df['Species']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [13]:
model.fit(x,y)

LinearRegression()

In [14]:
model.predict(x_test)

array([ 8.84875996e-05, -3.26854579e-02, -1.01834705e-01,  1.84240596e+00,
        1.44938775e+00,  1.02311961e+00,  1.66740449e+00,  7.45644153e-02,
        9.00622332e-01,  1.72019374e+00,  1.28451660e+00,  2.00181829e+00,
        1.18772685e+00,  1.39549109e-01, -2.16688605e-02, -1.58465961e-01,
       -3.85897565e-02,  1.81075169e+00, -8.13030749e-02,  1.74143264e+00,
       -3.39982044e-02,  3.35222953e-02, -1.22408563e-02,  1.09965570e+00,
        1.49592176e+00,  1.41725961e+00,  1.57522972e+00,  1.58832992e+00,
        1.20308259e+00,  1.60005592e+00])

In [15]:
x_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
11             4.8           3.4            1.6           0.2
18             5.7           3.8            1.7           0.3
13             4.3           3.0            1.1           0.1
112            6.8           3.0            5.5           2.1
133            6.3           2.8            5.1           1.5
69             5.6           2.5            3.9           1.1
149            5.9           3.0            5.1           1.8
41             4.5           2.3            1.3           0.3
93             5.0           2.3            3.3           1.0
125            7.2           3.2            6.0           1.8
51             6.4           3.2            4.5           1.5
135            7.7           3.0            6.1           2.3
75             6.6           3.0            4.4           1.4
44             5.1           3.8            1.9           0.4
17             5.1           3.5            1.4           0.3
32             5.2           4.1            1.5           0.1
1              4.9           3.0            1.4           0.2
113            5.7           2.5            5.0           2.0
37             4.9           3.1            1.5           0.1
103            6.3           2.9            5.6           1.8
16             5.4           3.9            1.3           0.4
31             5.4           3.4            1.5           0.4
19             5.1           3.8            1.5           0.3
71             6.1           2.8            4.0           1.3
77             6.7           3.0            5.0           1.7
72             6.3           2.5            4.9           1.5
126            6.2           2.8            4.8           1.8
138            6.0           3.0            4.8           1.8
50             7.0           3.2            4.7           1.4
127            6.1           3.0            4.9           1.8

In [16]:
y_test

11     0
18     0
13     0
112    2
133    2
69     1
149    2
41     0
93     1
125    2
51     1
135    2
75     1
44     0
17     0
32     0
1      0
113    2
37     0
103    2
16     0
31     0
19     0
71     1
77     1
72     1
126    2
138    2
50     1
127    2
Name: Species, dtype: int32

In [17]:
model.score(x,y)

0.9304223675331595

In [18]:
model.predict([[5.3,2.4,3.0,4.0]])

array([2.62485779])

In [19]:
model.predict([[5.0,3.6,1.4,0.2]])

array([-0.07610817])

In [20]:
model.predict([[6.2,3.4,5.4,2.3]])

array([1.98983334])