In [5]:
import numpy as np

In [6]:
my_arr= np.arange(1000000)
my_list=list(range(1000000))

In [7]:
%time for i in range(10): my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 31.7 ms


In [8]:
%time for i in range(10): my_list2 = [x*2 for x in my_list]

CPU times: total: 1.58 s
Wall time: 1.59 s


In [9]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
type(a)

numpy.ndarray

In [12]:
a.shape  #1D array

(6,)

In [13]:
b=np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
type(b)

numpy.ndarray

In [17]:
c=np.array([1,2,3,4,5,6,7,8,9],ndmin=2)   #2D array
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [18]:
c.shape

(1, 9)

In [21]:
d=np.array([1,2,3],dtype=complex)
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
b


array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
b.shape

(3, 2)

In [24]:
e=b.reshape(2,3)
e

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
s=np.array([1,2,3,4,5,6,7,8,9])
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
t=s.reshape(3,3)
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a=np.arange(24)  #Range from 0 to 23  
#arange(1st,2nd,3rd)....inclusive,exclusive,step_size
#24 -> 0,24,0
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
b=a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [33]:
x=np.array([1,2,3,4,5],dtype=np.int8)
x

array([1, 2, 3, 4, 5], dtype=int8)

In [34]:
x.itemsize

1

In [35]:
y=np.array([1,2,3,4,5],dtype=np.float32)
y

array([1., 2., 3., 4., 5.], dtype=float32)

In [36]:
y.itemsize

4

In [37]:
x=np.array([1,2,3,4,5])
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [38]:
y=x.copy()
y

array([1, 2, 3, 4, 5])

In [39]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [41]:
np.__version__

'1.21.5'

In [43]:
x=np.ones([3,3],dtype=int)
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
#empty array
x=np.empty([3,2],dtype=int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [45]:
x=np.ones(5)  #array of elements 1....5 is size of array
x

array([1., 1., 1., 1., 1.])

In [47]:
x=np.ones([3,3] ,dtype=int)  #array of elements 1
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [48]:
x*2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [49]:
x=[1,2,3,4,5]
a=np.asarray(x)
a

array([1, 2, 3, 4, 5])

In [53]:
x=[1,2,3,4,5,6,7,8,9]
a=np.asarray(x)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a[0:2]

array([1, 2])

In [65]:
a[0:3:2] #0th row to 3rd row....jump by 2...ie. 0 to 2

array([1, 3])

In [ ]:
a[]